# .github/workflows/publish-to-pypi.yml

name: Publish Python Package to PyPI

on:
  # Run this workflow whenever a new tag starting with 'v' is pushed
  push:
    tags:
      - 'v*'

jobs:
  publish-to-pypi:
    name: Build and publish Python package to PyPI
    runs-on: ubuntu-latest
    
    # This permission is required for trusted publishing
    permissions:
      id-token: write # Important for trusted publishing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: pip install build

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        # This action handles the OIDC token exchange and publishing
        uses: pypa/gh-action-pypi-publish@release/v1
